#!/bin/sh

APPDIR=$(dirname "$0")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/artnetP5.jar:$APPDIR/lib/hemesh-external.jar:$APPDIR/lib/hemesh.jar:$APPDIR/lib/javolution-6.1.0.jar:$APPDIR/lib/jts.jar:$APPDIR/lib/P2LX.jar:$APPDIR/lib/trove-3.1a1.jar:$APPDIR/lib/dome.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/gson-2.3.jar:$APPDIR/lib/P2LX.jar:$APPDIR/lib/jl1.0.jar:$APPDIR/lib/jsminim.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/tritonus_share.jar" dome "$@"
